### ISSUE TITLE
The `bg-surface-50-900-token` class does not exist.

### ISSUE THREAD

**Issue by MarizanneVis** [skeletonlabs/skeleton#1128]
### Current Behavior

Updating to v1.0.0 I get the following error:

```bash
node_modules\@skeletonlabs\skeleton\styles\tailwind.css:13:1: The `bg-surface-50-900-token` class does not exist. If `bg-surface-50-900-token` is a custom class, make sure it is defined within a `@layer` directive.
  Plugin: vite:css
  File: ./node_modules/@skeletonlabs/skeleton/styles/tailwind.css:13:1
  11 |  /* Typographical Settings */
  12 |  @import 'typography.css';
  13 |  
     |   ^
  14 |  /* Imports all Tailwind Elements */
  15 |  @import 'elements.css';
      at Input.error (.\node_modules\postcss\lib\input.js:148:16)
      at AtRule.error (.\node_modules\postcss\lib\node.js:60:32)
      at processApply (.\node_modules\tailwindcss\lib\lib\expandApplyAtRules.js:376:29)
      at .\node_modules\tailwindcss\lib\lib\expandApplyAtRules.js:524:9
      at .\node_modules\tailwindcss\lib\processTailwindFeatures.js:55:50
      at plugins (.\node_modules\tailwindcss\lib\plugin.js:38:63)
      at LazyResult.runOnRoot (.\node_modules\postcss\lib\lazy-result.js:339:16)   
      at LazyResult.runAsync (.\node_modules\postcss\lib\lazy-result.js:393:26)    
      at async compileCSS (./node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
      at async TransformContext.transform (./node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56) (x2)
CssSyntaxError: [postcss] .\node_modules\@skeletonlabs\skeleton\styles\tailwind.css:13:1: The `bg-surface-50-900-token` class does not exist. If `bg-surface-50-900-token` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error (.\node_modules\postcss\lib\input.js:148:16)
    at AtRule.error (.\node_modules\postcss\lib\node.js:60:32)
    at processApply (.\node_modules\tailwindcss\lib\lib\expandApplyAtRules.js:376:29)
    at .\node_modules\tailwindcss\lib\lib\expandApplyAtRules.js:524:9
    at .\node_modules\tailwindcss\lib\processTailwindFeatures.js:55:50
    at plugins (.\node_modules\tailwindcss\lib\plugin.js:38:63)
    at LazyResult.runOnRoot (.\node_modules\postcss\lib\lazy-result.js:339:16)     
    at LazyResult.runAsync (.\node_modules\postcss\lib\lazy-result.js:393:26)      
    at async compileCSS (./node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
    at async TransformContext.transform (./node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56)
Error: Not found: /favicon.ico
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:394:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:243:5)
    at #options.hooks.handle (/@fs/./node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

In `tailwind.config.cjs` I've had to switch the plugin require from `'@skeletonlabs/skeleton/tailwind/theme.cjs'` to `'@skeletonlabs/skeleton/tailwind/skeleton.cjs'` to fix another issue, but I can't find any other change that I've made

### Steps To Reproduce

1. Initialize project with v0.86.9
2. update package to v1.0.0
3. switch the plugin require from `'@skeletonlabs/skeleton/tailwind/theme.cjs'` to `'@skeletonlabs/skeleton/tailwind/skeleton.cjs'`
4. `npm run dev`

**Comment by endigo9740** [comment]
@MarizanneVis can you post the full contents of the following:

1. Your `tailwind.config.cjs`
2. The `/src/app.postcss`
3. A minimum the CSS imports in your root `/src/routes/+layout.svelte`

I've seen this error a number of times and it's typically a config error in one of these three files.

**Comment by S-L-Moore** [comment]
I'm seeing the same issue:
1) tailwind.config.cjs:
```
const config = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    require("path").join(
      require.resolve("@skeletonlabs/skeleton"),
      "../**/*.{html,js,svelte,ts}"
    ),
  ],

  theme: {
    extend: {},
  },

  plugins: [require("@skeletonlabs/skeleton/tailwind/skeleton.cjs")()],
};

module.exports = config;
```
2) /src/app.postcss
```
/* Write your global styles here, in PostCSS syntax */

html, body { @apply h-full overflow-hidden; }
```
3) /src/routes/+layout.svelte.. Don't have one of these, main.ts:
```
import "./app.postcss";

import '@skeletonlabs/skeleton/themes/theme-gold-nouveau.css';
import '@skeletonlabs/skeleton/styles/all.css';

import App from "./App.svelte";
```

**Comment by S-L-Moore** [comment]
nb. Noticed that some sections of the error message I'm seeing are different:
```
[postcss] /home/steve/Projects/VableII/node_modules/@skeletonlabs/skeleton/styles/tailwind.css:13:1: The `bg-surface-50-900-token` class does not exist. If `bg-surface-50-900-token` is a custom class, make sure it is defined within a `@layer` directive.
9:42:26 AM [vite] Internal server error: [postcss] /home/steve/Projects/VableII/node_modules/@skeletonlabs/skeleton/styles/tailwind.css:13:1: The `bg-surface-50-900-token` class does not exist. If `bg-surface-50-900-token` is a custom class, make sure it is defined within a `@layer` directive.
  Plugin: vite:css
  File: /home/steve/Projects/VableII/node_modules/@skeletonlabs/skeleton/styles/tailwind.css:13:1
  11 |  /* Typographical Settings */
  12 |  @import 'typography.css';
  13 |  
     |   ^
  14 |  /* Imports all Tailwind Elements */
  15 |  @import 'elements.css';
      at Input.error (/home/steve/Projects/VableII/node_modules/postcss/lib/input.js:148:16)
      at AtRule.error (/home/steve/Projects/VableII/node_modules/postcss/lib/node.js:60:32)
      at processApply (/home/steve/Projects/VableII/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:376:29)
      at /home/steve/Projects/VableII/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:524:9
      at /home/steve/Projects/VableII/node_modules/tailwindcss/lib/processTailwindFeatures.js:55:50
      at plugins (/home/steve/Projects/VableII/node_modules/tailwindcss/lib/index.js:38:63)
      at LazyResult.runOnRoot (/home/steve/Projects/VableII/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/home/steve/Projects/VableII/node_modules/postcss/lib/lazy-result.js:393:26)
      at async compileCSS (file:///home/steve/Projects/VableII/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:43820:25)
      at async TransformContext.transform (file:///home/steve/Projects/VableII/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:43310:55)
```

**Comment by endigo9740** [comment]
@S-L-Moore Per your issue, the Skeleton Tailwind plugin is not imported properly. Note the three leading dots, such as `...`:

```js
plugins: [
	// 3. Append the Skeleton plugin to the end of this list
	...require('@skeletonlabs/skeleton/tailwind/skeleton.cjs')()
]
```

Additionally, we do recommend you keep your global stylesheet `app.postcss` as the last imported. That way if you need to overwrite any of the prior imported styles, you can:

```ts
import '@skeletonlabs/skeleton/themes/theme-gold-nouveau.css';
import '@skeletonlabs/skeleton/styles/all.css';
import "./app.postcss";
```

**Comment by S-L-Moore** [comment]
I can confirm that was my issue, up & running on v1 now, thanks for the speedy pointer.

**Comment by endigo9740** [comment]
Closing due to inactivity. The messages above with Moore should point you down the right path though.
