### ISSUE TITLE
CodeBlock issue on safari

### ISSUE THREAD

**Issue by pvbhanuteja** [skeletonlabs/skeleton#2371]
### Current Behavior

Could not find the language 'plaintext', did you forget to load/include a language module?
Error: Unknown language: "plaintext"
    at _highlight (/Users/bhanu/repos/dev/my-skeleton-app/node_modules/highlight.js/lib/core.js:2107:13)
    at Object.highlight (/Users/bhanu/repos/dev/my-skeleton-app/node_modules/highlight.js/lib/core.js:1720:9)
    at /Users/bhanu/repos/dev/my-skeleton-app/node_modules/@skeletonlabs/skeleton/dist/utilities/CodeBlock/CodeBlock.svelte:41:37
    at Object.$$render (/Users/bhanu/repos/dev/my-skeleton-app/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at eval (/Users/bhanu/repos/dev/my-skeleton-app/src/routes/dashboard/+page.svelte:49:835)
    at Object.$$render (/Users/bhanu/repos/dev/my-skeleton-app/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.default (/Users/bhanu/repos/dev/my-skeleton-app/.svelte-kit/generated/root.svelte:45:41)
    at Object.default (/Users/bhanu/repos/dev/my-skeleton-app/src/routes/+layout.svelte:81:47)
    at /Users/bhanu/repos/dev/my-skeleton-app/node_modules/@skeletonlabs/skeleton/dist/components/AppShell/AppShell.svelte:54:64
    at Object.$$render (/Users/bhanu/repos/dev/my-skeleton-app/node_modules/svelte/src/runtime/internal/ssr.js:156:16)

### Expected Behavior

The default codeblock language type plaintext doesnt work on safari.

**Comment by endigo9740** [comment]
Hey @pvbhanuteja, we talk about setting up the requirements for Highlight.js here. Including steps for setting up the language modules that you require for your project:

https://www.skeleton.dev/utilities/codeblocks#configure-your-project

As far as I can recall, Highlight doesn't provide a module for `plaintext` (read no `language` specified). In the case of Skeleton we typically need something like this for terminal commands. So we opt for `shell`.

```
import shell from 'highlight.js/lib/languages/shell';
hljs.registerLanguage('shell', shell);
```

All in all, just make sure you have a `language` prop set and the correct module registered.

See Highlight's docs for more infoformation:

- https://highlightjs.org/#usage
- https://highlightjs.readthedocs.io/en/latest/supported-languages.html

**Comment by pvbhanuteja** [comment]
Hey @endigo9740 thanks for the response. Is there anyway I can skip the language prop. I don't want shell badge in my python/other lan codes.

**Comment by endigo9740** [comment]
If you're using Python or other languages, then install the appropriate language modules for those.

Python would be something like this:

```
import shell from 'highlight.js/lib/languages/python';
hljs.registerLanguage('python', python);
```
