### ISSUE TITLE
npm `create skeleton-app@0.0.23` errors out, but `npm create skeleton-app@0.0.21` works fine

### ISSUE THREAD

**Issue by riziles** [skeletonlabs/skeleton#886]
### Current Behavior

I stood up a little playground project a few weeks ago using `npm create skeleton-app@latest` and it worked great. Just tried to do a new one today, and it did not. Changed the version back to 0.0.21 and it worked fine.

Unfortunately, the error itself seems to be throwing an error:

```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2211:5)
    at out (file:///C:/Users/riziles/AppData/Local/npm-cache/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/creator.js:269:5)
    at createSkeleton (file:///C:/Users/riziles/AppData/Local/npm-cache/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/creator.js:108:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///C:/Users/riziles/AppData/Local/npm-cache/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/index.js:26:2) {
  code: 'ERR_INVALID_ARG_TYPE'
```

### Steps To Reproduce

1. run `npm create skeleton-app@0.0.21`
2. using npm@8.19.2, node@v18.12.1, Windows_NT 10.0.19044

### Anything else?

I love Skeleton so hard.

**Comment by Sarenor** [comment]
Works fine for me @riziles, could you provide a bit more context on where the error occured?
During the scaffolding with the CLI or during npm run dev?

Considering that it works when you downgrade to 0.92.2 I feel like you did not actually use the latest CLI but did grab the newest Skeleton which is going to conflict because the tailwind plugin hat a lot of breaking changes and your tailwind config now needs to look something like this:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'class',
	content: ['./src/**/*.{html,js,svelte,ts}', require('path').join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,js,svelte,ts}')],
	theme: {
		extend: {},
	},
	plugins: [require('@tailwindcss/forms'),require('@tailwindcss/typography'),require('@tailwindcss/line-clamp'),...require('@skeletonlabs/skeleton/tailwind/skeleton.cjs')()],
}
```
The ... spread operator and the () brackets are essential so that we can keep making changes to the plugin without breaking it for end users.

**Comment by riziles** [comment]
@Sarenor ,

The error occurs during scaffolding if I use `@latest`. The comment about downgrading to 0.92.2 was in reference to using 0.0.21. Here is the full error message I receive when using `@latest`. I'm a little puzzled by the `Unable to download settings file for VSCode` message. I am not running this inside of VS Code:

```
(node18) C:\LocalTemp\Repos\GitHub>npm create skeleton-app@latest skeleton9

create-skeleton-app version 0.0.23

Welcome to Skeleton 💀! A UI tookit for Svelte + Tailwind

This is BETA software; expect bugs and missing features.

Problems? Open an issue on https://github.com/skeletonlabs/skeleton/issues if none exists already.

√ Add type checking with TypeScript? » Yes, using TypeScript syntax
√ Add ESLint for code linting? ... No / Yes
√ Add Prettier for code formatting? ... No / Yes
√ Add Playwright for browser testing? ... No / Yes
√ Add Vitest for unit testing? ... No / Yes
√ Enable Svelte-Kit experimental inspector http://bit.ly/3Hu0BGf ? ... No / Yes
√ Pick tailwind plugins to add: »
√ Select a theme: » Skeleton
√ Which Skeleton app template? » Skeleton Welcome
Working: Creating base SvelteKit install.        
Working: Installing project dependencies.
Unable to download settings file for VSCode, please read manual instructions at https://skeleton.dev
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2211:5)
    at out (file:///C:/Users/riziles/AppData/Local/npm-cache/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/creator.js:269:5)
    at createSkeleton (file:///C:/Users/riziles/AppData/Local/npm-cache/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/creator.js:108:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///C:/Users/riziles/AppData/Local/npm-cache/_npx/ed0f586322dee443/node_modules/create-skeleton-app/src/index.js:26:2) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.12.1
npm ERR! code 1
npm ERR! path C:\LocalTemp\Repos\GitHub
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c create-skeleton-app skeleton9

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\riziles\AppData\Local\npm-cache\_logs\2023-01-27T14_51_10_444Z-debug-0.log
```

**Comment by cyborgdennett** [comment]
I have the same error.
Creating my-skeleton-app with a theme.

The dependencies in package.json are not filled for some reason

**Comment by cyborgdennett** [comment]
```json
"devDependencies": {
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^1.0.0",
		"@sveltejs/kit": "^1.0.0",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"tslib": "^2.4.1",
		"typescript": "^4.9.3",
		"vite": "^4.0.0",
		"vitest": "^0.25.3"
	},
```
These are what I get, where is skeleton dependency?

**Comment by cyborgdennett** [comment]
^ Above was the output with the example app template

Creating a Bare Bones project does give me the dependency's.
